version: '2'
services:

    # Application container
    php:
        container_name: project_php_apache
        build: .
        restart: unless-stopped
        volumes:
            - ./web:/var/www/html
        ports:
           - "80:80"
           - "443:443"
        environment:
            DEBUG: 'true'
#        links:
#          - db

    # Mysql Container
#    db:
#        container_name: mysql_5.6
#        image: mysql:5.6
#        ports:
#          - "3300:3300"
#        environment:
#          - MYSQL_ROOT_PASSWORD=admin
#          - MYSQL_DATABASE=admin